sudo: false
language: generic
env:
  matrix:
  - GHCVER=8.4.3 STACK_YAML=stack.yaml
install:
- mkdir -p ~/.local/bin
- travis_retry curl -L https://github.com/commercialhaskell/stack/releases/download/v1.7.1/stack-1.7.1-linux-x86_64.tar.gz
  | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
- export PATH=~/.local/bin:$PATH
- stack --no-terminal --version
script:
- stack setup --no-terminal
- stack update --no-terminal
- stack build -j2 --fast --no-terminal
- stack test --coverage --fast --no-terminal
after_script:
- travis_retry curl -L https://github.com/rubik/stack-hpc-coveralls/releases/download/v0.0.4.0/shc-linux-x64-8.0.1.tar.bz2
  | tar -xj
- "./shc tenhou-dl tenhou-dl-test"
cache:
  timeout: 2000
  directories:
  - "$HOME/.cabal"
  - "$HOME/.ghc"
  - "$HOME/.stack"
  - ".stack-work/"
  apt: true
